### PR TITLE
Add `nostd-libm` feature (#617) and prepare for 0.29.3

### LINKED ISSUE #620: Backport `nostd-libm` to 0.29
**What problem does this solve or what need does it fill?**

Due to dependency issues with Encase, Bevy would like to adopt the new `nostd-libm` feature, but on Glam 0.29 (e.g., 0.29.3). This would allow us to start using the new feature now while we await changes in other dependencies.

**Describe the solution you'd like**

I would like the feature backported to 0.29. I have already prepared a branch [here](https://github.com/bushrat011899/glam-rs/tree/0.29.3-nostd-libm) with a single [commit](https://github.com/bitshifter/glam-rs/commit/17cc0d7fb67292275747fbd42fa1df26969d938f) which I believe is sufficient to add the feature and prepare a 0.29.3 release.

**Describe alternatives you've considered**

Could take no action and wait for Encase to update, or for Bevy to find an alternate approach that would allow us to upgrade to 0.30.1.

**Additional context**

[This Discord Message](https://discord.com/channels/691052431525675048/692572690833473578/1352925641644838973) from a key Bevy maintainer expressed a desire for this path forward.

### PR DESCRIPTION
**Pull request by bushrat011899**
# Objective

- Fixes #620

## Solution

- Cherry-picks the changes from #617 
- Bumps the version to 0.29.3

## Code generation

- Modified templates to minimise Clippy lints in current Rust version. Refer to individual commits for specific actions taken.

## Testing and linting

- Linted

### CODE REVIEW

**Comment by bushrat011899** [comment]
Fixed most of the lints, but there are some issues around the `rykv` feature that I'm unsure how to resolve locally (can't get that feature to work locally so I can't really work on the lint issue). At a glance, looks like the `rkyv::from_archived` and/or `rkyv::to_archived` macros expect `archive_be` and `archive_le` features, which seems like a bug in the 0.7 version of Rkyv.

**Comment by aloucks** [comment]
I'm curious if this is actually a change in Rust 1.85 (or 1.84). When I compile with Rust **1.83**, I do not see the failure with the features. (I don't have 1.84 installed, so I didn't check it)

Example error message:
```
error: unexpected `cfg` condition value: `archive_le`
   --> src\features\impl_rkyv.rs:161:5
    |
161 |     impl_rkyv!(U64Vec3);
    |     ^^^^^^^^^^^^^^^^^^^
    |
    = note: expected values for `feature` are: `approx`, `bytecheck`, `bytemuck`, `core-simd`, `cuda`, `debug-glam-assert`, `default`, `fast-math`, `glam-assert`, `libm`, `mint`, `nostd-libm`, `rand`, `rkyv`, `scalar-math`, `serde`, and `std`
    = note: using a cfg inside a macro will use the cfgs from the destination crate and not the ones from the defining crate
    = help: try referring to `to_archived` crate for guidance on how handle this unexpected cfg
    = help: the macro `to_archived` may come from an old version of the `rkyv` crate, try updating your dependency with `cargo update -p rkyv`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
    = note: this error originates in the macro `to_archived` which comes from the expansion of the macro `impl_rkyv` (in Nightly builds, run with -Z macro-backtrace for more info)
```

rkyv `0.7` has that feature checked in the macro:

https://github.com/rkyv/rkyv/blob/6892a9cd5d6a78c8d753c3dd35bfd814b00afa69/rkyv/src/macros.rs#L71-L82

```rust
macro_rules! from_archived {
    ($expr:expr) => {{
        #[cfg(not(any(feature = "archive_le", feature = "archive_be")))]
        {
            $expr
        }
        #[cfg(any(feature = "archive_le", feature = "archive_be"))]
        {
            ($expr).value()
        }
    }};
}
```

If you define `archive_le` and `archive_be` in glam, you can fix the issue to things to almost compile on 1.85.

```
diff --git a/Cargo.toml b/Cargo.toml
index 3e81f83..699fce4 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,6 +16,8 @@ maintenance = { status = "actively-developed" }

 [features]
 default = ["std"]
+archive_le = ["rkyv/archive_le"]
+archive_be = ["rkyv/archive_be"]
``` 

I'm now seeing a different error on the codegen crate:

```
$ cargo +1.85 clippy --workspace --all-targets --all-features -- -D warnings
   Compiling rend v0.4.2
   Compiling rkyv v0.7.45
    Checking codegen v0.1.1 (D:\projects\glam-rs\codegen)
error[E0624]: method `get` is private
  --> codegen\src\main.rs:95:37
   |
95 |         let template_path = context.get("template_path").unwrap().as_str().unwrap();
   |                                     ^^^ private method
   |
  ::: C:\Users\Aaron\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tera-1.1.0\src\context.rs:84:5
   |
84 |     pub(crate) fn get(&self, index: &str) -> Option<&Value> {
   |     ------------------------------------------------------- private method defined here
```

**Comment by bushrat011899** [comment]
Yeah I'm not sure what the issue is, but I'm confident this is an existing issue (in the sense that I see this on 0.29.2 as well, not just in this PR). So I'd prefer to punt it as "if you have this issue, try upgrading to 0.30".

**Comment by bitshifter** [comment]
I'm not too worried about it but if you want to fix the cargo-deny check this change should do it https://github.com/bitshifter/glam-rs/pull/592/files

**Comment by bitshifter** [comment]
I've published 0.29.3 now.
